@startuml
package ui {
    [Checkout Screen]
    [Checkout ViewModel]
    interface interface1
}
note right
 display the application data
endnote
package domain {
    [Checkout Manager]
    interface interface2
}
note right
    responsible for encapsulating complex business logic, or simple business logic that is reused by multiple ViewModels
endnote
package data {
    [Checkout repo]
    interface interface3
 }
note right
     the data layer contains application data and business logic
end note

[interface1] -down-> [interface2]
[interface2] -down-> [interface3]
[Checkout ViewModel] -right-> [interface1] : exports
[Checkout Manager] -right-> [interface2] : exports
[Checkout repo] -right-> [interface3] : exports
[Checkout ViewModel] -up..> [Checkout Screen] : observes
[Checkout Screen] -down-> [Checkout ViewModel] : data


@enduml